#SV-68 - Added a new dart file to read articles and blogs.
Team-Uncodables/threeifbyspaceapp pull request #15
Opened 2022-11-18 23:30 UTC by Mehton

#SV-68 - Added a new dart file to read articles and blogs. This will be used as skeleton widget for all other text only pages in the app.

2022-11-19 00:45 UTC, jmarmstrong1207 requested changes

2022-11-19 00:45 UTC, jmarmstrong1207 commented on lib/main.dart
> +    home: Read(),
Stop using main.dart. DO NOT modify main.dart.

2022-11-19 00:52 UTC, jmarmstrong1207 commented
Only issue I see is that the spacing gets weird when the window size is changed. See if you can fix it before the sprint ends.
<img width="782" alt="Screenshot 2022-11-18 at 4 50 50 PM" src="https://user-images.githubusercontent.com/32995055/202825622-46fb4d86-8d9f-4824-b13b-8ce2415cda9a.png">

2022-11-19 21:39 UTC, Mehton commented
I will fix it in next sprint

2022-11-20 19:26 UTC, jmarmstrong1207 approved these changes

2022-11-20 19:27 UTC, merged